# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2024-11-11T18:19:29+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Param(BaseModel):
    key: Optional[str] = None
    value: Optional[str] = None


class ServiceTrackingParam(BaseModel):
    service: Optional[str] = None
    params: Optional[List[Param]] = None


class ResponseContext(BaseModel):
    visitorData: Optional[str] = None
    serviceTrackingParams: Optional[List[ServiceTrackingParam]] = None
    maxAgeSeconds: Optional[int] = None


class MiniplayerRenderer(BaseModel):
    playbackMode: Optional[str] = None


class Miniplayer(BaseModel):
    miniplayerRenderer: Optional[MiniplayerRenderer] = None


class PlayabilityStatus(BaseModel):
    status: Optional[str] = None
    playableInEmbed: Optional[bool] = None
    miniplayer: Optional[Miniplayer] = None
    contextParams: Optional[str] = None


class Format(BaseModel):
    itag: Optional[int] = None
    url: Optional[str] = None
    mimeType: Optional[str] = None
    bitrate: Optional[int] = None
    width: Optional[int] = None
    height: Optional[int] = None
    lastModified: Optional[str] = None
    contentLength: Optional[str] = None
    quality: Optional[str] = None
    fps: Optional[int] = None
    qualityLabel: Optional[str] = None
    projectionType: Optional[str] = None
    averageBitrate: Optional[int] = None
    audioQuality: Optional[str] = None
    approxDurationMs: Optional[str] = None
    audioSampleRate: Optional[str] = None
    audioChannels: Optional[int] = None


class InitRange(BaseModel):
    start: Optional[str] = None
    end: Optional[str] = None


class IndexRange(BaseModel):
    start: Optional[str] = None
    end: Optional[str] = None


class ColorInfo(BaseModel):
    primaries: Optional[str] = None
    transferCharacteristics: Optional[str] = None
    matrixCoefficients: Optional[str] = None


class AdaptiveFormat(BaseModel):
    itag: Optional[int] = None
    url: Optional[str] = None
    mimeType: Optional[str] = None
    bitrate: Optional[int] = None
    width: Optional[int] = None
    height: Optional[int] = None
    initRange: Optional[InitRange] = None
    indexRange: Optional[IndexRange] = None
    lastModified: Optional[str] = None
    contentLength: Optional[str] = None
    quality: Optional[str] = None
    fps: Optional[int] = None
    qualityLabel: Optional[str] = None
    projectionType: Optional[str] = None
    averageBitrate: Optional[int] = None
    approxDurationMs: Optional[str] = None
    colorInfo: Optional[ColorInfo] = None
    highReplication: Optional[bool] = None
    audioQuality: Optional[str] = None
    audioSampleRate: Optional[str] = None
    audioChannels: Optional[int] = None
    loudnessDb: Optional[float] = None


class StreamingData(BaseModel):
    expiresInSeconds: Optional[str] = None
    formats: Optional[List[Format]] = None
    adaptiveFormats: Optional[List[AdaptiveFormat]] = None


class Header(BaseModel):
    headerType: Optional[str] = None


class VideostatsPlaybackUrl(BaseModel):
    baseUrl: Optional[str] = None
    headers: Optional[List[Header]] = None


class VideostatsDelayplayUrl(BaseModel):
    baseUrl: Optional[str] = None
    headers: Optional[List[Header]] = None


class VideostatsWatchtimeUrl(BaseModel):
    baseUrl: Optional[str] = None
    headers: Optional[List[Header]] = None


class PtrackingUrl(BaseModel):
    baseUrl: Optional[str] = None
    headers: Optional[List[Header]] = None


class QoeUrl(BaseModel):
    baseUrl: Optional[str] = None
    headers: Optional[List[Header]] = None


class AtrUrl(BaseModel):
    baseUrl: Optional[str] = None
    elapsedMediaTimeSeconds: Optional[int] = None
    headers: Optional[List[Header]] = None


class PlaybackTracking(BaseModel):
    videostatsPlaybackUrl: Optional[VideostatsPlaybackUrl] = None
    videostatsDelayplayUrl: Optional[VideostatsDelayplayUrl] = None
    videostatsWatchtimeUrl: Optional[VideostatsWatchtimeUrl] = None
    ptrackingUrl: Optional[PtrackingUrl] = None
    qoeUrl: Optional[QoeUrl] = None
    atrUrl: Optional[AtrUrl] = None
    videostatsScheduledFlushWalltimeSeconds: Optional[List[int]] = None
    videostatsDefaultFlushIntervalSeconds: Optional[int] = None


class Run(BaseModel):
    text: Optional[str] = None


class Name(BaseModel):
    runs: Optional[List[Run]] = None


class CaptionTrack(BaseModel):
    baseUrl: Optional[str] = None
    name: Optional[Name] = None
    vssId: Optional[str] = None
    languageCode: Optional[str] = None
    kind: Optional[str] = None
    isTranslatable: Optional[bool] = None
    trackName: Optional[str] = None


class AudioTrack(BaseModel):
    captionTrackIndices: Optional[List[int]] = None


class PlayerCaptionsTracklistRenderer(BaseModel):
    captionTracks: Optional[List[CaptionTrack]] = None
    audioTracks: Optional[List[AudioTrack]] = None
    defaultAudioTrackIndex: Optional[int] = None


class Captions(BaseModel):
    playerCaptionsTracklistRenderer: Optional[PlayerCaptionsTracklistRenderer] = None


class Thumbnail1(BaseModel):
    url: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None


class Thumbnail(BaseModel):
    thumbnails: Optional[List[Thumbnail1]] = None


class VideoDetails(BaseModel):
    videoId: Optional[str] = None
    title: Optional[str] = None
    lengthSeconds: Optional[str] = None
    channelId: Optional[str] = None
    isOwnerViewing: Optional[bool] = None
    shortDescription: Optional[str] = None
    isCrawlable: Optional[bool] = None
    thumbnail: Optional[Thumbnail] = None
    allowRatings: Optional[bool] = None
    viewCount: Optional[str] = None
    author: Optional[str] = None
    isPrivate: Optional[bool] = None
    isUnpluggedCorpus: Optional[bool] = None
    isLiveContent: Optional[bool] = None


class AudioConfig(BaseModel):
    loudnessDb: Optional[float] = None
    perceptualLoudnessDb: Optional[float] = None
    enablePerFormatLoudness: Optional[bool] = None


class ExoPlayerConfig(BaseModel):
    useExoPlayer: Optional[bool] = None
    useAdaptiveBitrate: Optional[bool] = None
    maxInitialByteRate: Optional[int] = None
    minDurationForQualityIncreaseMs: Optional[int] = None
    maxDurationForQualityDecreaseMs: Optional[int] = None
    minDurationToRetainAfterDiscardMs: Optional[int] = None
    lowWatermarkMs: Optional[int] = None
    highWatermarkMs: Optional[int] = None
    lowPoolLoad: Optional[float] = None
    highPoolLoad: Optional[float] = None
    sufficientBandwidthOverhead: Optional[float] = None
    bufferChunkSizeKb: Optional[int] = None
    httpConnectTimeoutMs: Optional[int] = None
    httpReadTimeoutMs: Optional[int] = None
    numAudioSegmentsPerFetch: Optional[int] = None
    numVideoSegmentsPerFetch: Optional[int] = None
    minDurationForPlaybackStartMs: Optional[int] = None
    enableExoplayerReuse: Optional[bool] = None
    useRadioTypeForInitialQualitySelection: Optional[bool] = None
    blacklistFormatOnError: Optional[bool] = None
    enableBandaidHttpDataSource: Optional[bool] = None
    httpLoadTimeoutMs: Optional[int] = None
    canPlayHdDrm: Optional[bool] = None
    videoBufferSegmentCount: Optional[int] = None
    audioBufferSegmentCount: Optional[int] = None
    useAbruptSplicing: Optional[bool] = None
    minRetryCount: Optional[int] = None
    minChunksNeededToPreferOffline: Optional[int] = None
    secondsToMaxAggressiveness: Optional[int] = None
    enableSurfaceviewResizeWorkaround: Optional[bool] = None
    enableVp9IfThresholdsPass: Optional[bool] = None
    matchQualityToViewportOnUnfullscreen: Optional[bool] = None
    lowAudioQualityConnTypes: Optional[List[str]] = None
    useDashForLiveStreams: Optional[bool] = None
    enableLibvpxVideoTrackRenderer: Optional[bool] = None
    lowAudioQualityBandwidthThresholdBps: Optional[int] = None
    enableVariableSpeedPlayback: Optional[bool] = None
    preferOnesieBufferedFormat: Optional[bool] = None
    minimumBandwidthSampleBytes: Optional[int] = None
    useDashForOtfAndCompletedLiveStreams: Optional[bool] = None
    disableCacheAwareVideoFormatEvaluation: Optional[bool] = None
    useLiveDvrForDashLiveStreams: Optional[bool] = None
    cronetResetTimeoutOnRedirects: Optional[bool] = None
    emitVideoDecoderChangeEvents: Optional[bool] = None
    onesieVideoBufferLoadTimeoutMs: Optional[str] = None
    onesieVideoBufferReadTimeoutMs: Optional[str] = None
    libvpxEnableGl: Optional[bool] = None
    enableVp9EncryptedIfThresholdsPass: Optional[bool] = None
    enableOpus: Optional[bool] = None
    usePredictedBuffer: Optional[bool] = None
    maxReadAheadMediaTimeMs: Optional[int] = None
    useMediaTimeCappedLoadControl: Optional[bool] = None
    allowCacheOverrideToLowerQualitiesWithinRange: Optional[int] = None
    allowDroppingUndecodedFrames: Optional[bool] = None
    minDurationForPlaybackRestartMs: Optional[int] = None
    serverProvidedBandwidthHeader: Optional[str] = None
    liveOnlyPegStrategy: Optional[str] = None
    enableRedirectorHostFallback: Optional[bool] = None
    enableHighlyAvailableFormatFallbackOnPcr: Optional[bool] = None
    recordTrackRendererTimingEvents: Optional[bool] = None
    minErrorsForRedirectorHostFallback: Optional[int] = None
    nonHardwareMediaCodecNames: Optional[List[str]] = None
    enableVp9IfInHardware: Optional[bool] = None
    enableVp9EncryptedIfInHardware: Optional[bool] = None
    useOpusMedAsLowQualityAudio: Optional[bool] = None
    minErrorsForPcrFallback: Optional[int] = None
    useStickyRedirectHttpDataSource: Optional[bool] = None
    onlyVideoBandwidth: Optional[bool] = None
    useRedirectorOnNetworkChange: Optional[bool] = None
    enableMaxReadaheadAbrThreshold: Optional[bool] = None
    cacheCheckDirectoryWritabilityOnce: Optional[bool] = None
    predictorType: Optional[str] = None
    slidingPercentile: Optional[float] = None
    slidingWindowSize: Optional[int] = None
    maxFrameDropIntervalMs: Optional[int] = None
    ignoreLoadTimeoutForFallback: Optional[bool] = None
    serverBweMultiplier: Optional[int] = None
    drmMaxKeyfetchDelayMs: Optional[int] = None
    maxResolutionForWhiteNoise: Optional[int] = None
    whiteNoiseRenderEffectMode: Optional[str] = None
    enableLibvpxHdr: Optional[bool] = None
    enableCacheAwareStreamSelection: Optional[bool] = None
    useExoCronetDataSource: Optional[bool] = None
    whiteNoiseScale: Optional[int] = None
    whiteNoiseOffset: Optional[int] = None
    preventVideoFrameLaggingWithLibvpx: Optional[bool] = None
    enableMediaCodecHdr: Optional[bool] = None
    enableMediaCodecSwHdr: Optional[bool] = None
    liveOnlyWindowChunks: Optional[int] = None
    bearerMinDurationToRetainAfterDiscardMs: Optional[List[int]] = None
    forceWidevineL3: Optional[bool] = None
    useAverageBitrate: Optional[bool] = None
    useMedialibAudioTrackRendererForLive: Optional[bool] = None
    useExoPlayerV2: Optional[bool] = None
    logMediaRequestEventsToCsi: Optional[bool] = None
    onesieFixNonZeroStartTimeFormatSelection: Optional[bool] = None
    liveOnlyReadaheadStepSizeChunks: Optional[int] = None
    liveOnlyBufferHealthHalfLifeSeconds: Optional[int] = None
    liveOnlyMinBufferHealthRatio: Optional[float] = None
    liveOnlyMinLatencyToSeekRatio: Optional[int] = None
    manifestlessPartialChunkStrategy: Optional[str] = None
    ignoreViewportSizeWhenSticky: Optional[bool] = None
    enableLibvpxFallback: Optional[bool] = None
    disableLibvpxLoopFilter: Optional[bool] = None
    enableVpxMediaView: Optional[bool] = None
    hdrMinScreenBrightness: Optional[int] = None
    hdrMaxScreenBrightnessThreshold: Optional[int] = None
    onesieDataSourceAboveCacheDataSource: Optional[bool] = None
    httpNonplayerLoadTimeoutMs: Optional[int] = None
    numVideoSegmentsPerFetchStrategy: Optional[str] = None
    maxVideoDurationPerFetchMs: Optional[int] = None
    maxVideoEstimatedLoadDurationMs: Optional[int] = None
    estimatedServerClockHalfLife: Optional[int] = None
    estimatedServerClockStrictOffset: Optional[bool] = None
    minReadAheadMediaTimeMs: Optional[int] = None
    readAheadGrowthRate: Optional[int] = None
    useDynamicReadAhead: Optional[bool] = None
    useYtVodMediaSourceForV2: Optional[bool] = None
    enableV2Gapless: Optional[bool] = None
    useLiveHeadTimeMillis: Optional[bool] = None
    allowTrackSelectionWithUpdatedVideoItagsForExoV2: Optional[bool] = None
    maxAllowableTimeBeforeMediaTimeUpdateSec: Optional[int] = None
    enableDynamicHdr: Optional[bool] = None
    v2PerformEarlyStreamSelection: Optional[bool] = None
    v2UsePlaybackStreamSelectionResult: Optional[bool] = None
    v2MinTimeBetweenAbrReevaluationMs: Optional[int] = None
    avoidReusePlaybackAcrossLoadvideos: Optional[bool] = None
    enableInfiniteNetworkLoadingRetries: Optional[bool] = None
    reportExoPlayerStateOnTransition: Optional[bool] = None
    manifestlessSequenceMethod: Optional[str] = None
    useLiveHeadWindow: Optional[bool] = None
    enableDynamicHdrInHardware: Optional[bool] = None
    ultralowAudioQualityBandwidthThresholdBps: Optional[int] = None
    retryLiveNetNocontentWithDelay: Optional[bool] = None
    ignoreUnneededSeeksToLiveHead: Optional[bool] = None
    drmMetricsQoeLoggingFraction: Optional[float] = None
    liveNetNocontentMaximumErrors: Optional[int] = None
    slidingPercentileScalar: Optional[int] = None
    minAdaptiveVideoQuality: Optional[int] = None
    retryLiveEmptyChunkWithDelay: Optional[bool] = None
    platypusBackBufferDurationMs: Optional[int] = None


class NetworkProtocolConfig(BaseModel):
    useQuic: Optional[bool] = None


class AndroidMetadataNetworkConfig(BaseModel):
    coalesceRequests: Optional[bool] = None


class AndroidNetworkStackConfig(BaseModel):
    networkStack: Optional[str] = None
    androidMetadataNetworkConfig: Optional[AndroidMetadataNetworkConfig] = None


class AndroidMedialibConfig(BaseModel):
    isItag18MainProfile: Optional[bool] = None
    surfaceUnavailableIsFatal: Optional[bool] = None
    surfaceCreateTimeoutMs: Optional[int] = None
    viewportSizeFraction: Optional[float] = None


class Label(BaseModel):
    runs: Optional[List[Run]] = None


class AvailablePlaybackSpeed(BaseModel):
    label: Optional[Label] = None
    value: Optional[float] = None


class VariableSpeedConfig(BaseModel):
    availablePlaybackSpeeds: Optional[List[AvailablePlaybackSpeed]] = None
    androidVariableSpeedTimeoutSecs: Optional[int] = None
    enableVariableSpeedOnOtf: Optional[bool] = None


class DecodeQualityConfig(BaseModel):
    maximumVideoDecodeVerticalResolution: Optional[int] = None


class VrConfig(BaseModel):
    allowVr: Optional[bool] = None
    allowSubtitles: Optional[bool] = None
    showHqButton: Optional[bool] = None
    sphericalDirectionLoggingEnabled: Optional[bool] = None
    enableAndroidVr180MagicWindow: Optional[bool] = None


class AndroidPlayerStatsConfig(BaseModel):
    usePblForAttestationReporting: Optional[bool] = None
    usePblForHeartbeatReporting: Optional[bool] = None
    usePblForPlaybacktrackingReporting: Optional[bool] = None
    usePblForQoeReporting: Optional[bool] = None
    changeCpnOnFatalPlaybackError: Optional[bool] = None


class RetryConfig(BaseModel):
    retryEligibleErrors: Optional[List[str]] = None
    retryUnderSameConditionAttempts: Optional[int] = None
    retryWithNewSurfaceAttempts: Optional[int] = None
    progressiveFallbackOnNonNetworkErrors: Optional[bool] = None
    l3FallbackOnDrmErrors: Optional[bool] = None
    retryAfterCacheRemoval: Optional[bool] = None
    widevineL3EnforcedFallbackOnDrmErrors: Optional[bool] = None
    exoProxyableFormatFallback: Optional[bool] = None
    maxPlayerRetriesWhenNetworkUnavailable: Optional[int] = None
    suppressFatalErrorAfterStop: Optional[bool] = None
    fallbackToSwDecoderOnFormatDecodeError: Optional[bool] = None


class CmsPathProbeConfig(BaseModel):
    cmsPathProbeDelayMs: Optional[int] = None


class DynamicReadaheadConfig(BaseModel):
    maxReadAheadMediaTimeMs: Optional[int] = None
    minReadAheadMediaTimeMs: Optional[int] = None
    readAheadGrowthRateMs: Optional[int] = None
    readAheadWatermarkMarginRatio: Optional[int] = None
    minReadAheadWatermarkMarginMs: Optional[int] = None
    maxReadAheadWatermarkMarginMs: Optional[int] = None
    shouldIncorporateNetworkActiveState: Optional[bool] = None


class MediaUstreamerRequestConfig(BaseModel):
    enableVideoPlaybackRequest: Optional[bool] = None
    videoPlaybackUstreamerConfig: Optional[str] = None
    videoPlaybackPostEmptyBody: Optional[bool] = None
    isVideoPlaybackRequestIdempotent: Optional[bool] = None


class PredictedReadaheadConfig(BaseModel):
    minReadaheadMs: Optional[int] = None
    maxReadaheadMs: Optional[int] = None


class MediaFetchRetryConfig(BaseModel):
    initialDelayMs: Optional[int] = None
    backoffFactor: Optional[float] = None
    maximumDelayMs: Optional[int] = None
    jitterFactor: Optional[float] = None


class NextRequestPolicy(BaseModel):
    targetAudioReadaheadMs: Optional[int] = None
    targetVideoReadaheadMs: Optional[int] = None


class ServerReadaheadConfig(BaseModel):
    enable: Optional[bool] = None
    nextRequestPolicy: Optional[NextRequestPolicy] = None


class SabrClientConfig(BaseModel):
    defaultBackOffTimeMs: Optional[int] = None
    enableHostFallback: Optional[bool] = None
    primaryProbingDelayMs: Optional[int] = None
    maxFailureAttemptsBeforeFallback: Optional[int] = None
    enableServerInitiatedHostFallback: Optional[bool] = None


class MediaCommonConfig(BaseModel):
    dynamicReadaheadConfig: Optional[DynamicReadaheadConfig] = None
    mediaUstreamerRequestConfig: Optional[MediaUstreamerRequestConfig] = None
    predictedReadaheadConfig: Optional[PredictedReadaheadConfig] = None
    mediaFetchRetryConfig: Optional[MediaFetchRetryConfig] = None
    mediaFetchMaximumServerErrors: Optional[int] = None
    mediaFetchMaximumNetworkErrors: Optional[int] = None
    mediaFetchMaximumErrors: Optional[int] = None
    serverReadaheadConfig: Optional[ServerReadaheadConfig] = None
    useServerDrivenAbr: Optional[bool] = None
    sabrClientConfig: Optional[SabrClientConfig] = None


class TaskCoordinatorConfig(BaseModel):
    prefetchCoordinatorBufferedPositionMillisRelease: Optional[int] = None
    prefetchCoordinatorBufferedPositionMillisPause: Optional[int] = None


class PlayerConfig(BaseModel):
    audioConfig: Optional[AudioConfig] = None
    exoPlayerConfig: Optional[ExoPlayerConfig] = None
    networkProtocolConfig: Optional[NetworkProtocolConfig] = None
    androidNetworkStackConfig: Optional[AndroidNetworkStackConfig] = None
    androidMedialibConfig: Optional[AndroidMedialibConfig] = None
    variableSpeedConfig: Optional[VariableSpeedConfig] = None
    decodeQualityConfig: Optional[DecodeQualityConfig] = None
    vrConfig: Optional[VrConfig] = None
    androidPlayerStatsConfig: Optional[AndroidPlayerStatsConfig] = None
    retryConfig: Optional[RetryConfig] = None
    cmsPathProbeConfig: Optional[CmsPathProbeConfig] = None
    mediaCommonConfig: Optional[MediaCommonConfig] = None
    taskCoordinatorConfig: Optional[TaskCoordinatorConfig] = None


class PlayerStoryboardSpecRenderer(BaseModel):
    spec: Optional[str] = None
    recommendedLevel: Optional[int] = None


class Storyboards(BaseModel):
    playerStoryboardSpecRenderer: Optional[PlayerStoryboardSpecRenderer] = None


class PlayerAttestationRenderer(BaseModel):
    challenge: Optional[str] = None


class Attestation(BaseModel):
    playerAttestationRenderer: Optional[PlayerAttestationRenderer] = None


class YouTubeResponse(BaseModel):
    responseContext: Optional[ResponseContext] = None
    playabilityStatus: Optional[PlayabilityStatus] = None
    streamingData: Optional[StreamingData] = None
    playbackTracking: Optional[PlaybackTracking] = None
    captions: Optional[Captions] = None
    videoDetails: Optional[VideoDetails] = None
    playerConfig: Optional[PlayerConfig] = None
    storyboards: Optional[Storyboards] = None
    trackingParams: Optional[str] = None
    attestation: Optional[Attestation] = None
    adBreakHeartbeatParams: Optional[str] = None
