ACTIONS = {
    "bite": "bit",
    "cuddle": "cuddled",
    "feed": "fed",
    "hug": "hugged",
    "kiss": "kissed",
    "pat": "patted",
    "poke": "poked",
    "punch": "punched",
    "slap": "slapped",
    "smug": "smugged at",
    "tickle": "tickled",
    "neko": "showed a neko to",
    "waifu": "showed a waifu to",
    "husbando": "showed a husbando to",
    "kitsune": "showed a kitsune to",
    "lurk": "lurked at",
    "shoot": "shot",
    "sleep": "slept with",
    "shrug": "shrugged at",
    "stare": "stared at",
    "wave": "waved at",
    "smile": "smiled at",
    "peck": "pecked",
    "wink": "winked at",
    "blush": "blushed at",
    "yeet": "yeeted",
    "think": "thought about",
    "highfive": "high-fived",
    "bored": "is bored with",
    "nom": "nommed",
    "yawn": "yawned at",
    "facepalm": "facepalmed at",
    "happy": "is happy with",
    "baka": "called baka",
    "nod": "nods at",
    "nope": "noped at",
    "dance": "danced with",
    "handshake": "shook hands with",
    "cry": "cried with",
    "pout": "pouted at",
    "handhold": "held hands with",
    "thumbsup": "gave a thumbs up to",
    "laugh": "laughed with",
    "lick": "licked",
    "bully": "bullied",
    "bonk": "bonked",
    "cringe": "cringed at",
    "awoo": "awooed at",
    "fuck": "fucked",
    "spank": "spanked",
    "nutkick": "nutkicked",
    "angry": "got angry at",
    "run": "ran from",
    "kick": "kicked"
}